---
# This task file to generate service account key pair
# k8s use these cert to sign service account tokens tha can be used to authenticate with service accounts crated within cluster
- name: Copy the service-account certificate signing request
  copy:
    src: service-account-csr.json
    dest: "{{ CERT_DIR }}"
    mode: 0755
  tags: cf

- name: Generate the  service-account client certificate and private key
  command: bash -c 'cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes service-account-csr.json | cfssljson -bare service-account'
  args:
    chdir:  "{{ CERT_DIR }}"
#    creates:  "{{ PKI_DIR }}/service-account-key.pem"